//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AC_GROUP()
        {
            this.AC_SUB_GROUP = new HashSet<AC_SUB_GROUP>();
        }
    
        public Nullable<decimal> SS_FACTY_SS_FACTY_ID { get; set; }
        public Nullable<double> PROGRAM1_ID { get; set; }
        public string NATURE { get; set; }
        public string GROUP_NAME { get; set; }
        public string GROUP_ID { get; set; }
        public double AC_GP_ID { get; set; }
        public System.DateTime ACTION_DT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_SUB_GROUP> AC_SUB_GROUP { get; set; }
        public virtual PROGRAM1 PROGRAM1 { get; set; }
    }
}
