//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_LEDGER
    {
        public decimal AC_LG_ID { get; set; }
        public Nullable<decimal> AC_SG_ID { get; set; }
        public Nullable<decimal> AC_SG_AC_SG_ID { get; set; }
        public string LEDGER_ID { get; set; }
        public Nullable<double> CR_OP_BAL { get; set; }
        public Nullable<double> DR_OP_BAL { get; set; }
        public Nullable<decimal> DEP_RATE { get; set; }
        public string LEDGER_NAME { get; set; }
        public Nullable<double> GROUP_TYPE { get; set; }
        public string BANK_AC_TYPE { get; set; }
        public Nullable<double> DEP_AC_ID { get; set; }
        public string USERNAME { get; set; }
        public string COURSE_CODE { get; set; }
        public System.DateTime ACTION_DT { get; set; }
        public string CTYPE { get; set; }
    
        public virtual AC_SUB_GROUP AC_SUB_GROUP { get; set; }
    }
}
