//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_SUB_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AC_SUB_GROUP()
        {
            this.AC_LEDGER = new HashSet<AC_LEDGER>();
        }
    
        public Nullable<decimal> AC_GP_AC_GP_ID { get; set; }
        public string SGROUP_NAME { get; set; }
        public string SGROUP_ID { get; set; }
        public Nullable<double> AC_GP_ID { get; set; }
        public decimal AC_SG_ID { get; set; }
        public string COURSE_TYPE_CODE { get; set; }
        public System.DateTime ACTION_DT { get; set; }
    
        public virtual AC_GROUP AC_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_LEDGER> AC_LEDGER { get; set; }
    }
}
