//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCCHARTOFACCOUNT
    {
        public string LGID { get; set; }
        public string ACCNO { get; set; }
        public string ACCNM { get; set; }
        public string ACCNMSH { get; set; }
        public decimal ACCLVL { get; set; }
        public string NATURE { get; set; }
        public Nullable<decimal> GTYPE { get; set; }
        public string DRCR { get; set; }
        public string DEPID { get; set; }
        public Nullable<decimal> DEPRATE { get; set; }
        public string RFLGID { get; set; }
        public string RFACCNO { get; set; }
        public string PTFLAG { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> OPNBAL { get; set; }
        public Nullable<decimal> MONBAL { get; set; }
        public Nullable<decimal> CURBAL { get; set; }
        public string MAJPRDCD { get; set; }
        public string ALLOCCATCD { get; set; }
        public Nullable<decimal> ALLOCPCT { get; set; }
        public string SUBLGID { get; set; }
        public string COMPID { get; set; }
        public string LOCID { get; set; }
        public string PRJID { get; set; }
        public string SFUSRID { get; set; }
        public string DBUSRNM { get; set; }
        public string ACTTP { get; set; }
        public System.DateTime ACTDT { get; set; }
    
        public virtual ACCCOMPANY ACCCOMPANY { get; set; }
        public virtual ACCLOCATION ACCLOCATION { get; set; }
        public virtual ACCPROJECT ACCPROJECT { get; set; }
    }
}
