//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCCOMPANYGROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCCOMPANYGROUP()
        {
            this.ACCCOMPANY = new HashSet<ACCCOMPANY>();
        }
    
        public string COMPGPID { get; set; }
        public string COMPGPNM { get; set; }
        public string COMPGPBAN { get; set; }
        public string COMPGPSNM { get; set; }
        public string COMPGPSNMBAN { get; set; }
        public string COMPGPADDR { get; set; }
        public string COMPGPLOC { get; set; }
        public string COMPGPPH { get; set; }
        public string COMPGPFAX { get; set; }
        public string COMPGPEMAIL { get; set; }
        public string COMPGPWWW { get; set; }
        public byte[] COMPGPLOGO { get; set; }
        public string DEFSTS { get; set; }
        public string SFUSRID { get; set; }
        public string DBUSRNM { get; set; }
        public string ACTTP { get; set; }
        public System.DateTime ACTDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCCOMPANY> ACCCOMPANY { get; set; }
    }
}
