//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCMONTHCLOSE
    {
        public System.DateTime MONDT { get; set; }
        public string PTFLAG { get; set; }
        public Nullable<decimal> DRAMT { get; set; }
        public Nullable<decimal> CRAMT { get; set; }
        public string LGID { get; set; }
        public string COMPID { get; set; }
        public string PRJID { get; set; }
        public string SFUSRID { get; set; }
        public string DBUSRNM { get; set; }
        public string ACTTP { get; set; }
        public System.DateTime ACTDT { get; set; }
    
        public virtual ACCCOMPANY ACCCOMPANY { get; set; }
        public virtual ACCPROJECT ACCPROJECT { get; set; }
    }
}
