//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATTENDANCE_M()
        {
            this.ATTENDANCE_D = new HashSet<ATTENDANCE_D>();
        }
    
        public double ATTENDANCE_M_ID { get; set; }
        public string SEMESTER { get; set; }
        public string YEAR { get; set; }
        public string PROGRAM { get; set; }
        public Nullable<double> PROGRAM_CODE { get; set; }
        public string COURSE_CODE { get; set; }
        public string COURSE_TITLE { get; set; }
        public string SECTION { get; set; }
        public string COURSE_TEACHER { get; set; }
        public string BATCH { get; set; }
        public Nullable<System.DateTime> ATTENDANCE_DATE { get; set; }
        public System.DateTime ACTION_DT { get; set; }
        public Nullable<double> AC_LG_ID { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D1 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D2 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D3 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D4 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D5 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D6 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D7 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D8 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D9 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D10 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D11 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D12 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D13 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D14 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D15 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D16 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D17 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D18 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D19 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D20 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D21 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D22 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D23 { get; set; }
        public Nullable<System.DateTime> CLASS_NO_1_D24 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTENDANCE_D> ATTENDANCE_D { get; set; }
    }
}
