//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTMARK_M_CT
    {
        public string ID { get; set; }
        public string SEMESTER { get; set; }
        public string USER_ID { get; set; }
        public System.DateTime ACTION_DT { get; set; }
        public Nullable<double> YEAR { get; set; }
        public string SID { get; set; }
        public string STUDENT_NAME { get; set; }
        public Nullable<double> AC_LG_ID { get; set; }
        public Nullable<double> PROGRAM1_ID { get; set; }
        public string UNIVERSITY_NAME { get; set; }
    }
}
