//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALSHEETDTL
    {
        public string BSDID { get; set; }
        public string BSMID { get; set; }
        public string LGID { get; set; }
        public string NMSHDTL { get; set; }
        public Nullable<decimal> BSDSEQ { get; set; }
        public string ADDTP { get; set; }
        public Nullable<decimal> DGRP { get; set; }
        public string SFUSRID { get; set; }
        public string DBUSRNM { get; set; }
        public string ACTTP { get; set; }
        public System.DateTime ACTDT { get; set; }
    
        public virtual BALSHEETMST BALSHEETMST { get; set; }
    }
}
