//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_LEND_INFO
    {
        public string LEND_ID { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public string MEM_ID { get; set; }
        public Nullable<decimal> EMP_ID { get; set; }
        public string BOOK_ID { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public string BOOK_STATUS { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string SUB_ID { get; set; }
    
        public virtual EMP_INFO EMP_INFO { get; set; }
    }
}
