//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGETMST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUDGETMST()
        {
            this.BUDGETDTL = new HashSet<BUDGETDTL>();
        }
    
        public string BUDMID { get; set; }
        public System.DateTime BUDDT { get; set; }
        public string PTFLAG { get; set; }
        public string COMPID { get; set; }
        public string LOCID { get; set; }
        public string PRJID { get; set; }
        public string BGRPMID { get; set; }
        public string SFUSRID { get; set; }
        public string DBUSRNM { get; set; }
        public string ACTTP { get; set; }
        public System.DateTime ACTDT { get; set; }
        public string ORDID { get; set; }
    
        public virtual ACCCOMPANY ACCCOMPANY { get; set; }
        public virtual ACCLOCATION ACCLOCATION { get; set; }
        public virtual ACCPROJECT ACCPROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUDGETDTL> BUDGETDTL { get; set; }
    }
}
