//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHART
    {
        public string ACCNO { get; set; }
        public string ACCNM { get; set; }
        public string RFACCNO { get; set; }
        public string PTFLAG { get; set; }
        public decimal ACCLVL { get; set; }
        public string DRCR { get; set; }
        public string NATURE { get; set; }
    }
}
