//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENT_SEMESTER
    {
        public string PROGRAM_ID { get; set; }
        public string PROGRAM { get; set; }
        public string PROGRAM_DETAILS { get; set; }
        public Nullable<double> SEMESTER_ID { get; set; }
    }
}
