//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMP_INFO()
        {
            this.BOOK_LEND_INFO = new HashSet<BOOK_LEND_INFO>();
        }
    
        public decimal EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public string GENDER { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string PHONE_NO { get; set; }
        public string PRE_ADD { get; set; }
        public string PER_ADD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> DESIG_ID { get; set; }
        public byte[] PHOTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_LEND_INFO> BOOK_LEND_INFO { get; set; }
        public virtual DESIGNATION DESIGNATION { get; set; }
    }
}
