//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEND_INFO_M
    {
        public double LEND_INFO_M_ID { get; set; }
        public string CIRD_NUMBER { get; set; }
        public Nullable<double> STUDENT_ID { get; set; }
        public string STUDENT_NAME { get; set; }
        public string MOBILE { get; set; }
        public System.DateTime ACTION_DT { get; set; }
        public string ADRESS { get; set; }
        public string SEMESTER { get; set; }
        public Nullable<double> YEAR { get; set; }
        public string PROGRAM { get; set; }
    }
}
