//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER_INFO
    {
        public string MEM_ID { get; set; }
        public string MEM_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> JOIN_DATE { get; set; }
        public string PRE_ADD { get; set; }
        public string PER_ADD { get; set; }
        public string MOBILE_NO { get; set; }
        public string REFERENCE { get; set; }
        public string EMAIL { get; set; }
        public string CARD_ID { get; set; }
        public byte[] PHOTO { get; set; }
    
        public virtual CARD CARD { get; set; }
    }
}
