//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFER_D
    {
        public Nullable<double> RID { get; set; }
        public string ID { get; set; }
        public string USER_ID { get; set; }
        public System.DateTime ACTION_DT { get; set; }
        public string COURSE_CODE { get; set; }
        public string STATUS { get; set; }
        public Nullable<double> PCH { get; set; }
        public string REMARKS { get; set; }
        public Nullable<double> AC_LG_ID { get; set; }
        public Nullable<double> CREDIT { get; set; }
        public string INSTRUCTOR_NAME { get; set; }
        public string INSTRUCTOR_ID { get; set; }
        public string TIME_SCHEDULE { get; set; }
        public string DAY { get; set; }
        public string ROOM_NO { get; set; }
        public string LNAME { get; set; }
        public Nullable<double> ROOM_CODE { get; set; }
        public Nullable<double> TIME_SCHEDULE_CODE { get; set; }
        public Nullable<double> DAYS_CODE { get; set; }
        public string BATCH { get; set; }
    }
}
