//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFER_COURSE_D
    {
        public string PROGRAM_CODE { get; set; }
        public string USER_ID { get; set; }
        public System.DateTime ACTION_DT { get; set; }
        public string COURSE_CODE { get; set; }
        public Nullable<double> CREDIT { get; set; }
        public Nullable<double> OFFER_MID { get; set; }
    }
}
