//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFUSERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SFUSERS()
        {
            this.SFUSERSGROUP = new HashSet<SFUSERSGROUP>();
        }
    
        public string SFUSRID { get; set; }
        public string USRNM { get; set; }
        public string USRFNM { get; set; }
        public string USRLNM { get; set; }
        public string USRPWD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFUSERSGROUP> SFUSERSGROUP { get; set; }
    }
}
