//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EDUCATION
    {
        public string ID { get; set; }
        public string NAME_OF_DEGREE { get; set; }
        public string BOARD_UNIVERSITB { get; set; }
        public Nullable<double> YEAR { get; set; }
        public string DIVISION_CLASS { get; set; }
        public string PERCENTAGE { get; set; }
        public string INSTITUTION { get; set; }
        public Nullable<decimal> CGPA { get; set; }
        public Nullable<decimal> CGPAWF { get; set; }
        public string GOLDEN { get; set; }
        public string EDU_ID { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
    }
}
