//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIALBALTHREECOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRIALBALTHREECOA()
        {
            this.TRIALBALFOURCOA = new HashSet<TRIALBALFOURCOA>();
        }
    
        public string TBTHCAID { get; set; }
        public string TBTWCAID { get; set; }
        public string THLGID { get; set; }
        public string THNMSH { get; set; }
        public Nullable<decimal> THTBSEQ { get; set; }
        public Nullable<decimal> THRPTTAG { get; set; }
        public string THADDTP { get; set; }
        public Nullable<decimal> THACCLVL { get; set; }
        public Nullable<decimal> THNAT { get; set; }
        public Nullable<decimal> THOPBAL { get; set; }
        public Nullable<decimal> THDRAMT { get; set; }
        public Nullable<decimal> THCRAMT { get; set; }
        public Nullable<decimal> THCLBAL { get; set; }
        public string SFUSRID { get; set; }
        public string DBUSRNM { get; set; }
        public string ACTTP { get; set; }
        public System.DateTime ACTDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIALBALFOURCOA> TRIALBALFOURCOA { get; set; }
        public virtual TRIALBALTWOCOA TRIALBALTWOCOA { get; set; }
    }
}
