//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIALBALTWOCOAPROJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRIALBALTWOCOAPROJ()
        {
            this.TRIALBALTHREECOAPROJ = new HashSet<TRIALBALTHREECOAPROJ>();
        }
    
        public string TBTWPJID { get; set; }
        public string TBONPJID { get; set; }
        public string TWLGID { get; set; }
        public string TWNMSH { get; set; }
        public Nullable<decimal> TWTBSEQ { get; set; }
        public Nullable<decimal> TWRPTTAG { get; set; }
        public string TWADDTP { get; set; }
        public Nullable<decimal> TWACCLVL { get; set; }
        public Nullable<decimal> TWNAT { get; set; }
        public string PRJID { get; set; }
        public Nullable<decimal> TWOPBAL { get; set; }
        public Nullable<decimal> TWDRAMT { get; set; }
        public Nullable<decimal> TWCRAMT { get; set; }
        public Nullable<decimal> TWCLBAL { get; set; }
        public string SFUSRID { get; set; }
        public string DBUSRNM { get; set; }
        public string ACTTP { get; set; }
        public System.DateTime ACTDT { get; set; }
    
        public virtual TRIALBALONECOAPROJ TRIALBALONECOAPROJ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIALBALTHREECOAPROJ> TRIALBALTHREECOAPROJ { get; set; }
    }
}
