//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIALBALONECOAPROJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRIALBALONECOAPROJ()
        {
            this.TRIALBALTWOCOAPROJ = new HashSet<TRIALBALTWOCOAPROJ>();
        }
    
        public string TBONPJID { get; set; }
        public string ONLGID { get; set; }
        public string ONNMSH { get; set; }
        public Nullable<decimal> ONTBSEQ { get; set; }
        public Nullable<decimal> ONRPTTAG { get; set; }
        public string ONADDTP { get; set; }
        public Nullable<decimal> ONACCLVL { get; set; }
        public Nullable<decimal> ONNAT { get; set; }
        public string COMPID { get; set; }
        public string PRJID { get; set; }
        public Nullable<decimal> ONOPBAL { get; set; }
        public Nullable<decimal> ONDRAMT { get; set; }
        public Nullable<decimal> ONCRAMT { get; set; }
        public Nullable<decimal> ONCLBAL { get; set; }
        public string SFUSRID { get; set; }
        public string DBUSRNM { get; set; }
        public string ACTTP { get; set; }
        public System.DateTime ACTDT { get; set; }
    
        public virtual ACCCOMPANY ACCCOMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIALBALTWOCOAPROJ> TRIALBALTWOCOAPROJ { get; set; }
    }
}
