//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUTION_INFO
    {
        public double TUTION_INFO_ID { get; set; }
        public Nullable<double> STUDENT_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<double> SEMESTER_ID { get; set; }
        public Nullable<double> YEAR { get; set; }
        public Nullable<double> TUTION_FEE { get; set; }
        public Nullable<double> ADMISSION_FEE { get; set; }
        public Nullable<double> REG_FEE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<double> COLLECTION_AMOUNT { get; set; }
        public string CTYPE { get; set; }
        public string MRNO { get; set; }
        public Nullable<double> WAIVER_AMT { get; set; }
        public Nullable<double> SEMESTER_FEE { get; set; }
    }
}
