//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataMigration.Win.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_GROUP_MAP
    {
        public Nullable<decimal> GP_ID { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_TYPE { get; set; }
    }
}
