//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_Semester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_Semester()
        {
            this.Aca_Class = new HashSet<Aca_Class>();
            this.Aca_Exam = new HashSet<Aca_Exam>();
            this.Aca_OfferedCourse = new HashSet<Aca_OfferedCourse>();
            this.Adm_AdmissionExam = new HashSet<Adm_AdmissionExam>();
            this.User_Account = new HashSet<User_Account>();
            this.User_ProfileChangeAudit = new HashSet<User_ProfileChangeAudit>();
            this.User_Student = new HashSet<User_Student>();
            this.User_Student1 = new HashSet<User_Student>();
        }
    
        public long Id { get; set; }
        public int SemesterNo { get; set; }
        public string Name { get; set; }
        public int TermId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public short Year { get; set; }
        public string AcademicSession { get; set; }
        public byte StatusEnumId { get; set; }
        public byte ProgramTypeEnumId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsRegistrationSemester { get; set; }
        public byte EnabledRegistrationTypeEnumId { get; set; }
        public Nullable<System.DateTime> RegistrationStartDate { get; set; }
        public Nullable<System.DateTime> RegistrationEndDate { get; set; }
        public bool IsEnableLateRegFee { get; set; }
        public Nullable<System.DateTime> LateRegFeeStartDate { get; set; }
        public float LateRegFeeAmount { get; set; }
        public float MaximumUGCredit { get; set; }
        public float MinimumUGCredit { get; set; }
        public float MaximumPGCredit { get; set; }
        public float MinimumPGCredit { get; set; }
        public System.DateTime ExamPermitPublishDate { get; set; }
        public float CurrentDropPercentage { get; set; }
        public int NewStudentIdPrefix { get; set; }
        public int NewStudentSuffix { get; set; }
        public int SectionTolarange { get; set; }
        public bool IsTpeEnable { get; set; }
        public bool IsForceTpeSubmit { get; set; }
        public float MinimumGradePointForRetake { get; set; }
        public int SemesterDurationEnumId { get; set; }
        public Nullable<int> StartingMonthEnumId { get; set; }
        public bool IsEnable { get; set; }
        public bool IsOpenBulkRegistration { get; set; }
        public bool IsOpenOnlineRegistration { get; set; }
        public bool IsCloseStudentProfileRegistration { get; set; }
        public bool CanCancelCompletedSemesterCourse { get; set; }
        public string RegistrationMessage { get; set; }
        public float RegistrationAllowedPaymentDueUpto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_Class> Aca_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_Exam> Aca_Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_OfferedCourse> Aca_OfferedCourse { get; set; }
        public virtual Aca_StudyTerm Aca_StudyTerm { get; set; }
        public virtual Aca_StudyTerm Aca_StudyTerm1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adm_AdmissionExam> Adm_AdmissionExam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Account> User_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_ProfileChangeAudit> User_ProfileChangeAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Student> User_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Student> User_Student1 { get; set; }
    }
}
