//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_QuestionOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_QuestionOption()
        {
            this.Aca_OnlineExamResultDetail = new HashSet<Aca_OnlineExamResultDetail>();
        }
    
        public int Id { get; set; }
        public int QuestionBankId { get; set; }
        public string Name { get; set; }
        public string OptionImagePath { get; set; }
        public bool IsCorrectAnswer { get; set; }
        public int OrderId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public Nullable<System.DateTime> LastChanged { get; set; }
        public Nullable<int> LastChangedById { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_OnlineExamResultDetail> Aca_OnlineExamResultDetail { get; set; }
        public virtual Aca_QuestionBank Aca_QuestionBank { get; set; }
    }
}
