//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_OnlineExamTakenByStudent
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int OnlineExamId { get; set; }
        public float ObtainedTotalMark { get; set; }
        public byte AttendanceTypeEnumId { get; set; }
        public bool IsResultPublished { get; set; }
        public string Remark { get; set; }
        public string History { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
    
        public virtual Aca_OnlineExam Aca_OnlineExam { get; set; }
        public virtual User_Student User_Student { get; set; }
    }
}
