//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_ClassAttendanceSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_ClassAttendanceSetting()
        {
            this.Aca_ClassAttendance = new HashSet<Aca_ClassAttendance>();
            this.Aca_ClassAttendanceSmsLog = new HashSet<Aca_ClassAttendanceSmsLog>();
        }
    
        public long Id { get; set; }
        public long ClassId { get; set; }
        public Nullable<long> RoutineId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int EmployeeId { get; set; }
        public byte ClassTypeEnumId { get; set; }
        public bool IsLocked { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
    
        public virtual Aca_Class Aca_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassAttendance> Aca_ClassAttendance { get; set; }
        public virtual Aca_ClassRoutine Aca_ClassRoutine { get; set; }
        public virtual User_Employee User_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassAttendanceSmsLog> Aca_ClassAttendanceSmsLog { get; set; }
    }
}
