//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_HomeWorkSubmission
    {
        public int Id { get; set; }
        public int HomeworkId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public int SubmissionStatusEnumId { get; set; }
        public bool Checked { get; set; }
        public int TeacherId { get; set; }
        public string Feedback { get; set; }
        public string Remark { get; set; }
        public string History { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
        public string SubmittedText { get; set; }
        public float ObtainedMark { get; set; }
    
        public virtual Aca_HomeWork Aca_HomeWork { get; set; }
        public virtual User_Employee User_Employee { get; set; }
        public virtual User_Student User_Student { get; set; }
    }
}
