//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_MarkDistributionPolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_MarkDistributionPolicy()
        {
            this.Aca_MarkDistributionPolicyComponent = new HashSet<Aca_MarkDistributionPolicyComponent>();
            this.Aca_OfferedCourse = new HashSet<Aca_OfferedCourse>();
            this.Aca_OfferedCourse1 = new HashSet<Aca_OfferedCourse>();
            this.Aca_OfferedCourse2 = new HashSet<Aca_OfferedCourse>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public float CreditHour { get; set; }
        public float TotalMark { get; set; }
        public byte CourseCategoryEnumId { get; set; }
        public float ConvertPercentage { get; set; }
        public byte ExamTypeEnumId { get; set; }
        public bool IsFixedPolicy { get; set; }
        public byte StatusEnumId { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public long StartSemesterId { get; set; }
        public Nullable<long> EndSemesterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_MarkDistributionPolicyComponent> Aca_MarkDistributionPolicyComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_OfferedCourse> Aca_OfferedCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_OfferedCourse> Aca_OfferedCourse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_OfferedCourse> Aca_OfferedCourse2 { get; set; }
    }
}
