//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_MarkDistributionPolicyComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_MarkDistributionPolicyComponent()
        {
            this.Aca_MarkDistributionPolicyBreakdown = new HashSet<Aca_MarkDistributionPolicyBreakdown>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long PolicyId { get; set; }
        public byte TestTypeEnumId { get; set; }
        public float DefaultTotalMark { get; set; }
        public float ConvertPercentage { get; set; }
        public bool IsFixedPolicy { get; set; }
        public int BestCount { get; set; }
        public string Remark { get; set; }
        public bool IsDeleted { get; set; }
        public int SerNo { get; set; }
    
        public virtual Aca_MarkDistributionPolicy Aca_MarkDistributionPolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_MarkDistributionPolicyBreakdown> Aca_MarkDistributionPolicyBreakdown { get; set; }
    }
}
