//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_Class()
        {
            this.Aca_ClassAttendance = new HashSet<Aca_ClassAttendance>();
            this.Aca_ClassAttendanceSetting = new HashSet<Aca_ClassAttendanceSetting>();
            this.Aca_ClassAttendanceSmsLog = new HashSet<Aca_ClassAttendanceSmsLog>();
            this.Aca_ClassMaterialFileMap = new HashSet<Aca_ClassMaterialFileMap>();
            this.Aca_ClassNotice = new HashSet<Aca_ClassNotice>();
            this.Aca_ClassRoutine = new HashSet<Aca_ClassRoutine>();
            this.Aca_ClassTakenByEmployee = new HashSet<Aca_ClassTakenByEmployee>();
            this.Aca_ClassTakenByStudent = new HashSet<Aca_ClassTakenByStudent>();
            this.Aca_ClassWaiverStudent = new HashSet<Aca_ClassWaiverStudent>();
            this.Aca_ClassWaiverStudent1 = new HashSet<Aca_ClassWaiverStudent>();
        }
    
        public long Id { get; set; }
        public int ProgramId { get; set; }
        public int DepartmentId { get; set; }
        public long CurriculumCourseId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int ClassNo { get; set; }
        public int ClassSectionId { get; set; }
        public int StudyLevelTermId { get; set; }
        public long SemesterId { get; set; }
        public byte ProgramTypeEnumId { get; set; }
        public short RegularCapacity { get; set; }
        public byte StatusEnumId { get; set; }
        public Nullable<int> CampusId { get; set; }
        public long RegularExamMarkDistributionPolicyId { get; set; }
        public Nullable<long> ReferredExamMarkDistributionPolicyId { get; set; }
        public Nullable<long> BacklogExamMarkDistributionPolicyId { get; set; }
        public Nullable<int> StudentBatchId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDasbleOnlineRegistration { get; set; }
        public string History { get; set; }
        public bool IsMidTermHardCopySubmitted { get; set; }
        public bool IsFinalTermHardCopySubmitted { get; set; }
        public bool IsBlockStudentPanelResult { get; set; }
        public bool IsSpecialUnlock { get; set; }
        public Nullable<System.DateTime> UnlockExpiryDate { get; set; }
        public string LockUnlockHistory { get; set; }
        public bool FacultyCanAddRoutine { get; set; }
        public bool FacultyCanEditRoutine { get; set; }
    
        public virtual Aca_ClassSection Aca_ClassSection { get; set; }
        public virtual Aca_CurriculumCourse Aca_CurriculumCourse { get; set; }
        public virtual Aca_DeptBatch Aca_DeptBatch { get; set; }
        public virtual Aca_Program Aca_Program { get; set; }
        public virtual Aca_Semester Aca_Semester { get; set; }
        public virtual Aca_StudyLevelTerm Aca_StudyLevelTerm { get; set; }
        public virtual General_Campus General_Campus { get; set; }
        public virtual HR_Department HR_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassAttendance> Aca_ClassAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassAttendanceSetting> Aca_ClassAttendanceSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassAttendanceSmsLog> Aca_ClassAttendanceSmsLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassMaterialFileMap> Aca_ClassMaterialFileMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassNotice> Aca_ClassNotice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassRoutine> Aca_ClassRoutine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassTakenByEmployee> Aca_ClassTakenByEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassTakenByStudent> Aca_ClassTakenByStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassWaiverStudent> Aca_ClassWaiverStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassWaiverStudent> Aca_ClassWaiverStudent1 { get; set; }
    }
}
