//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_ExamSupple
    {
        public int Id { get; set; }
        public long ExamId { get; set; }
        public bool IsOpenTheorySuppleApplyForStudent { get; set; }
        public bool IsOpenNonTheorySuppleApplyForStudent { get; set; }
        public System.DateTime SuppleApplicationLastDate { get; set; }
        public bool IsOpenTheorySuppleApplyForAdmin { get; set; }
        public bool IsOpenNonTheorySuppleApplyForAdmin { get; set; }
        public float SuppleApplyAllowedPaymentDueUpto { get; set; }
        public int MaxTimeCanApplyForOneTheory { get; set; }
        public int MaxTimeCanApplyForOneNonTheory { get; set; }
        public float ReferredSuppleExamFee { get; set; }
        public float BackLogSuppleExamFee { get; set; }
        public bool IsPublishedSuppleAdmitCard { get; set; }
        public float SuppleAdmitCardDownloadPaymentDueUpto { get; set; }
        public bool IsOpenTheorySuppleMarkInput { get; set; }
        public bool IsOpenNonTheorySuppleMarkInput { get; set; }
        public float AutoGradeGraceMarkForPass { get; set; }
        public bool IsPublishTheorySuppleResult { get; set; }
        public bool IsPublishNonTheorySuppleResult { get; set; }
        public float SuppleResultAllowedPaymentDueUpto { get; set; }
        public string StudentsInstructionsForApply { get; set; }
        public string FacultyInstructionsForMarkEntry { get; set; }
        public string StudentApplyConfirmationMessage { get; set; }
    
        public virtual Aca_Exam Aca_Exam { get; set; }
    }
}
