//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_OnlineClass
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime ClassDateTime { get; set; }
        public float ClassDuration { get; set; }
        public int ProgramId { get; set; }
        public long CurriculumCourseId { get; set; }
        public byte ClassMediaEnumId { get; set; }
        public string ClassUrl { get; set; }
        public string Remark { get; set; }
        public string History { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
        public string InquiryMobileNumber { get; set; }
        public string SyllabusInformation { get; set; }
        public bool IsRecurring { get; set; }
        public Nullable<byte> RecurringDayEnumId { get; set; }
    
        public virtual Aca_CurriculumCourse Aca_CurriculumCourse { get; set; }
        public virtual Aca_Program Aca_Program { get; set; }
    }
}
