//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_ExamRoll
    {
        public long Id { get; set; }
        public int StudentId { get; set; }
        public long ExamId { get; set; }
        public int ExamRoll { get; set; }
    
        public virtual Aca_Exam Aca_Exam { get; set; }
        public virtual User_Student User_Student { get; set; }
    }
}
