//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_StudyTerm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_StudyTerm()
        {
            this.Aca_Semester = new HashSet<Aca_Semester>();
            this.Aca_Semester1 = new HashSet<Aca_Semester>();
            this.Aca_StudyLevelTerm = new HashSet<Aca_StudyLevelTerm>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte TermNo { get; set; }
        public string SemesterName { get; set; }
        public bool IsEnabled { get; set; }
        public int SemesterDurationEnumId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_Semester> Aca_Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_Semester> Aca_Semester1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_StudyLevelTerm> Aca_StudyLevelTerm { get; set; }
    }
}
