//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_CreditTransferCourses
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int CreditTransfarId { get; set; }
        public Nullable<long> CurriculumCourseId { get; set; }
        public string TransferedCourseCode { get; set; }
        public string TransferedCourseName { get; set; }
        public float AcceptedCourseCredit { get; set; }
        public string AcceptedGrade { get; set; }
        public float AcceptedGradePoint { get; set; }
        public string Remarks { get; set; }
        public string History { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
    
        public virtual Aca_CreditTransfer Aca_CreditTransfer { get; set; }
        public virtual Aca_CurriculumCourse Aca_CurriculumCourse { get; set; }
        public virtual User_Student User_Student { get; set; }
    }
}
