//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_OfferedCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_OfferedCourse()
        {
            this.Aca_OfferedCourseForCurriculum = new HashSet<Aca_OfferedCourseForCurriculum>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public long CurriculumCourseId { get; set; }
        public int StudyLevelTermId { get; set; }
        public long SemesterId { get; set; }
        public long SemesterLevelTermId { get; set; }
        public long RegularExamMarkDistributionPolicyId { get; set; }
        public long ReferredExamMarkDistributionPolicyId { get; set; }
        public long BacklogExamMarkDistributionPolicyId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Aca_MarkDistributionPolicy Aca_MarkDistributionPolicy { get; set; }
        public virtual Aca_MarkDistributionPolicy Aca_MarkDistributionPolicy1 { get; set; }
        public virtual Aca_MarkDistributionPolicy Aca_MarkDistributionPolicy2 { get; set; }
        public virtual Aca_Semester Aca_Semester { get; set; }
        public virtual Aca_StudyLevelTerm Aca_StudyLevelTerm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_OfferedCourseForCurriculum> Aca_OfferedCourseForCurriculum { get; set; }
    }
}
