//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_Curriculum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_Curriculum()
        {
            this.Aca_CurriculumCourse = new HashSet<Aca_CurriculumCourse>();
            this.Aca_CurriculumStudentMap = new HashSet<Aca_CurriculumStudentMap>();
            this.User_Student = new HashSet<User_Student>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int Year { get; set; }
        public string Session { get; set; }
        public int CurriculumNo { get; set; }
        public int ProgramId { get; set; }
        public string Description { get; set; }
        public bool IsValid { get; set; }
        public bool IsOffering { get; set; }
        public float TotalCourse { get; set; }
        public int GradingPolicyId { get; set; }
        public float CourseRequireForGraduation { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Aca_GradingPolicy Aca_GradingPolicy { get; set; }
        public virtual Aca_Program Aca_Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_CurriculumCourse> Aca_CurriculumCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_CurriculumStudentMap> Aca_CurriculumStudentMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Student> User_Student { get; set; }
    }
}
