//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_TPEQuestionAnswer
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string AnswerTitle { get; set; }
        public float Rating { get; set; }
    
        public virtual Aca_TPEQuestion Aca_TPEQuestion { get; set; }
    }
}
