//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_CreditTransfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aca_CreditTransfer()
        {
            this.Aca_CreditTransferCourses = new HashSet<Aca_CreditTransferCourses>();
        }
    
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int PreviousUniversityId { get; set; }
        public float PreviousCGPA { get; set; }
        public Nullable<float> CGPAAccepted { get; set; }
        public float CreditAccepted { get; set; }
        public string FormerStudentId { get; set; }
        public string FormerProgramName { get; set; }
        public string FormerMajor { get; set; }
        public string FormerMinor { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public bool IsCalculateWithCurrentCGPA { get; set; }
        public bool IsPrintCourcesInTranscript { get; set; }
        public string Reason { get; set; }
        public string Remarks { get; set; }
        public int OrderNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
        public bool IsInternalDepartmentChange { get; set; }
    
        public virtual User_Student User_Student { get; set; }
        public virtual Aca_CreditTransferInstitute Aca_CreditTransferInstitute { get; set; }
        public virtual User_Account User_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_CreditTransferCourses> Aca_CreditTransferCourses { get; set; }
    }
}
