//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_DegreeCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adm_DegreeCategory()
        {
            this.User_Education = new HashSet<User_Education>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public byte DegreeEquivalentEnumId { get; set; }
        public byte BoardTypeEnumId { get; set; }
        public int OrderNo { get; set; }
        public bool IsEnable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Education> User_Education { get; set; }
    }
}
