//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAcnt_Ledger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAcnt_Ledger()
        {
            this.BAcnt_VoucherDetail = new HashSet<BAcnt_VoucherDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CodeName { get; set; }
        public byte TypeEnumId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsGroup { get; set; }
        public Nullable<double> OpeningBalance { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public string Remark { get; set; }
        public string History { get; set; }
        public bool IsDeleted { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
        public bool IsBank { get; set; }
    
        public virtual BAcnt_Branch BAcnt_Branch { get; set; }
        public virtual BAcnt_CompanyAccount BAcnt_CompanyAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAcnt_VoucherDetail> BAcnt_VoucherDetail { get; set; }
    }
}
