//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAcnt_Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAcnt_Voucher()
        {
            this.BAcnt_VoucherDetail = new HashSet<BAcnt_VoucherDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string VoucherNo { get; set; }
        public int VoucherTypeId { get; set; }
        public byte VoucherStatusEnumId { get; set; }
        public string Remark { get; set; }
        public string History { get; set; }
        public bool IsDeleted { get; set; }
        public string Narration { get; set; }
        public byte JournalTypeEnumId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string ManualSlipId { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeDate { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
    
        public virtual Acnt_OfficialBank Acnt_OfficialBank { get; set; }
        public virtual BAcnt_Branch BAcnt_Branch { get; set; }
        public virtual BAcnt_CompanyAccount BAcnt_CompanyAccount { get; set; }
        public virtual BAcnt_VoucherType BAcnt_VoucherType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAcnt_VoucherDetail> BAcnt_VoucherDetail { get; set; }
    }
}
