//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public General_Room()
        {
            this.Aca_ClassRoutine = new HashSet<Aca_ClassRoutine>();
        }
    
        public long Id { get; set; }
        public string RoomNo { get; set; }
        public string Name { get; set; }
        public int OrderNo { get; set; }
        public int FloorId { get; set; }
        public int CapacityRegular { get; set; }
        public int CapacityAdmission { get; set; }
        public byte TypeEnumId { get; set; }
        public byte StatusEnumId { get; set; }
        public long BuildingId { get; set; }
        public float Length { get; set; }
        public float Width { get; set; }
        public int DepartmentId { get; set; }
        public bool IsShareable { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassRoutine> Aca_ClassRoutine { get; set; }
        public virtual General_Building General_Building { get; set; }
        public virtual General_Floor General_Floor { get; set; }
        public virtual HR_Department HR_Department { get; set; }
    }
}
