//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public General_File()
        {
            this.Aca_ClassMaterialFileMap = new HashSet<Aca_ClassMaterialFileMap>();
        }
    
        public long Id { get; set; }
        public byte TypeEnumId { get; set; }
        public string Name { get; set; }
        public string DiskPath { get; set; }
        public bool IsDeleted { get; set; }
        public string ContentType { get; set; }
        public int SizeInByte { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public long ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassMaterialFileMap> Aca_ClassMaterialFileMap { get; set; }
    }
}
