//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_AllSmsLog
    {
        public long Id { get; set; }
        public string MobileNumber { get; set; }
        public byte TypeEnumId { get; set; }
        public string SmsText { get; set; }
        public byte DeliveryStatusEnumId { get; set; }
        public Nullable<int> SentToUserId { get; set; }
        public Nullable<long> ObjId { get; set; }
        public string DeliveryErrorText { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
    
        public virtual User_Account User_Account { get; set; }
    }
}
