//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_AppointmentHistory
    {
        public long Id { get; set; }
        public int EmployeeId { get; set; }
        public int PositionId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsActing { get; set; }
        public byte HistoryTypeEnumId { get; set; }
        public bool IsPrimary { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
    
        public virtual HR_Department HR_Department { get; set; }
        public virtual HR_Position HR_Position { get; set; }
        public virtual User_Employee User_Employee { get; set; }
    }
}
