//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmpLeaveApplication
    {
        public int Id { get; set; }
        public int LeaveAllocationSettingsId { get; set; }
        public int EmployeeId { get; set; }
        public byte LeaveTypeEnumId { get; set; }
        public System.DateTime LeaveFrom { get; set; }
        public System.DateTime LeaveTill { get; set; }
        public float LeaveHour { get; set; }
        public string LeaveReason { get; set; }
        public byte StatusEnumId { get; set; }
        public Nullable<int> RecommendByEmployeeId { get; set; }
        public string Remarks { get; set; }
        public string History { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual HR_EmpLeaveAllocationSettings HR_EmpLeaveAllocationSettings { get; set; }
        public virtual User_Employee User_Employee { get; set; }
        public virtual User_Employee User_Employee1 { get; set; }
    }
}
