//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_MonthlyPayslip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_MonthlyPayslip()
        {
            this.HR_MonthlyPayslipDetails = new HashSet<HR_MonthlyPayslipDetails>();
        }
    
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int PayrollId { get; set; }
        public int SalarySettingsId { get; set; }
        public float TotalAddition { get; set; }
        public float TotalDeduction { get; set; }
        public bool IsDraft { get; set; }
        public string Remarks { get; set; }
        public string History { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual HR_Payroll HR_Payroll { get; set; }
        public virtual HR_SalarySettings HR_SalarySettings { get; set; }
        public virtual User_Employee User_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_MonthlyPayslipDetails> HR_MonthlyPayslipDetails { get; set; }
    }
}
