//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SalarySettings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_SalarySettings()
        {
            this.HR_MonthlyPayslip = new HashSet<HR_MonthlyPayslip>();
            this.HR_SalarySettingsDetails = new HashSet<HR_SalarySettingsDetails>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte SalaryTypeEnumId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public bool IsCurrent { get; set; }
        public bool IsExcludedFromAutoGeneration { get; set; }
        public string History { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> NextPromotionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_MonthlyPayslip> HR_MonthlyPayslip { get; set; }
        public virtual User_Employee User_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_SalarySettingsDetails> HR_SalarySettingsDetails { get; set; }
    }
}
