//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SalaryTemplateDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_SalaryTemplateDetails()
        {
            this.HR_SalaryTemplateDetails1 = new HashSet<HR_SalaryTemplateDetails>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SalaryTemplateId { get; set; }
        public byte SalaryTypeEnumId { get; set; }
        public byte CategoryTypeEnumId { get; set; }
        public float OrderNo { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
    
        public virtual HR_SalaryTemplate HR_SalaryTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_SalaryTemplateDetails> HR_SalaryTemplateDetails1 { get; set; }
        public virtual HR_SalaryTemplateDetails HR_SalaryTemplateDetails2 { get; set; }
    }
}
