//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_SalaryTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_SalaryTemplate()
        {
            this.HR_LeaveAllocationTemplateDetails = new HashSet<HR_LeaveAllocationTemplateDetails>();
            this.HR_SalaryTemplateDetails = new HashSet<HR_SalaryTemplateDetails>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsAutoCalcSalaryFromAttend { get; set; }
        public bool IsEnable { get; set; }
        public string History { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
        public int OrderNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_LeaveAllocationTemplateDetails> HR_LeaveAllocationTemplateDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_SalaryTemplateDetails> HR_SalaryTemplateDetails { get; set; }
    }
}
