//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Htl_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Htl_Room()
        {
            this.Htl_HostelBuildingStudentMap = new HashSet<Htl_HostelBuildingStudentMap>();
        }
    
        public int Id { get; set; }
        public int HostelBuildingId { get; set; }
        public int FloorId { get; set; }
        public string RoomNumber { get; set; }
        public int Seat { get; set; }
        public int Bathroom { get; set; }
        public int Veranda { get; set; }
        public bool HasAC { get; set; }
        public int Occupied { get; set; }
        public int Vaccancy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Htl_Floor Htl_Floor { get; set; }
        public virtual Htl_HostalBuilding Htl_HostalBuilding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Htl_HostelBuildingStudentMap> Htl_HostelBuildingStudentMap { get; set; }
    }
}
