//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_PurchaseRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_PurchaseRequisition()
        {
            this.Inv_InventoryPurchaseRequisitionMap = new HashSet<Inv_InventoryPurchaseRequisitionMap>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> RequisitionDate { get; set; }
        public Nullable<int> RequisitionByUserId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Purpose { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ApprovedByUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_InventoryPurchaseRequisitionMap> Inv_InventoryPurchaseRequisitionMap { get; set; }
    }
}
