//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ItemDescription
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string CompanyItemBarcode { get; set; }
        public Nullable<System.DateTime> WarrentyDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LastChanged { get; set; }
        public Nullable<int> LastChangedById { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
