//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ProductCategoryDetails
    {
        public int Id { get; set; }
        public int ProductCategoryId { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> UnitTypeEnumId { get; set; }
        public Nullable<int> WarrningQuantity { get; set; }
        public string Details { get; set; }
        public Nullable<bool> HasBarcode { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    }
}
