//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_Requisition()
        {
            this.Inv_ItemAllocationRequisitionMap = new HashSet<Inv_ItemAllocationRequisitionMap>();
            this.Inv_RequestedItem = new HashSet<Inv_RequestedItem>();
            this.Inv_RequisitionDetails = new HashSet<Inv_RequisitionDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RequestedByEmployeeId { get; set; }
        public Nullable<System.DateTime> RequisitionDate { get; set; }
        public Nullable<System.DateTime> RequireDate { get; set; }
        public string Purpose { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ReferencedByEmployeeId { get; set; }
        public Nullable<int> IssuedOrReleaseByUserId { get; set; }
        public Nullable<int> ApprovedByAdminId { get; set; }
        public Nullable<int> ReceivedByEmployeeId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RequisitionStatusId { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<int> DeliveredById { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_ItemAllocationRequisitionMap> Inv_ItemAllocationRequisitionMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_RequestedItem> Inv_RequestedItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_RequisitionDetails> Inv_RequisitionDetails { get; set; }
    }
}
