//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_PurchaseRequisitionDetail
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public int PurchaseRequisitionId { get; set; }
        public int UnitTypeEnumId { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Inv_ProductCategory Inv_ProductCategory { get; set; }
    }
}
