//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_ItemAllocationRequisitionMap
    {
        public int Id { get; set; }
        public Nullable<int> ItemAllocationId { get; set; }
        public Nullable<int> RequisitionId { get; set; }
    
        public virtual Inv_ItemAllocation Inv_ItemAllocation { get; set; }
        public virtual Inv_Requisition Inv_Requisition { get; set; }
    }
}
