//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lib_Borrower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lib_Borrower()
        {
            this.Lib_BookActivityLog = new HashSet<Lib_BookActivityLog>();
            this.Lib_BookCopyTransaction = new HashSet<Lib_BookCopyTransaction>();
            this.Lib_BorrowerActivityLog = new HashSet<Lib_BorrowerActivityLog>();
            this.Lib_Fine = new HashSet<Lib_Fine>();
        }
    
        public int Id { get; set; }
        public byte BorrowerTypeEnumId { get; set; }
        public decimal FineAmount { get; set; }
        public short BorrowLimit { get; set; }
        public decimal CreditLimit { get; set; }
        public byte BorrowerStatusEnumId { get; set; }
        public decimal TotalFine { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lib_BookActivityLog> Lib_BookActivityLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lib_BookCopyTransaction> Lib_BookCopyTransaction { get; set; }
        public virtual User_Account User_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lib_BorrowerActivityLog> Lib_BorrowerActivityLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lib_Fine> Lib_Fine { get; set; }
    }
}
