//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lib_BookCopyTransaction
    {
        public long Id { get; set; }
        public int BorrowerId { get; set; }
        public long BookCopyId { get; set; }
        public System.DateTime BorrowedDate { get; set; }
        public long IssuedById { get; set; }
        public System.DateTime ExpectedReturnDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<long> CollectedById { get; set; }
        public Nullable<decimal> Fine { get; set; }
    
        public virtual Lib_BookCopy Lib_BookCopy { get; set; }
        public virtual Lib_Borrower Lib_Borrower { get; set; }
    }
}
