//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lib_BorrowerActivityLog
    {
        public long Id { get; set; }
        public int BorrowerId { get; set; }
        public byte BorrowerActivityEnumId { get; set; }
        public System.DateTime DoneOn { get; set; }
    
        public virtual Lib_Borrower Lib_Borrower { get; set; }
    }
}
