//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lib_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lib_Book()
        {
            this.Lib_BookDeptMap = new HashSet<Lib_BookDeptMap>();
            this.Lib_BookAuthorMap = new HashSet<Lib_BookAuthorMap>();
            this.Lib_BookCopy = new HashSet<Lib_BookCopy>();
            this.Lib_BookSubjectMap = new HashSet<Lib_BookSubjectMap>();
        }
    
        public long Id { get; set; }
        public int RecordId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string SubSubTitle { get; set; }
        public string Publisher { get; set; }
        public string PublicationPlace { get; set; }
        public string PublicationYear { get; set; }
        public string Edition { get; set; }
        public string ISBN { get; set; }
        public string Description { get; set; }
        public string Bibliography { get; set; }
        public string LcClassification { get; set; }
        public string DeweyClass { get; set; }
        public string Series { get; set; }
        public string ISSN { get; set; }
        public string Volume { get; set; }
        public string Note { get; set; }
        public byte BookStatusEnumId { get; set; }
        public string Responsibility { get; set; }
        public string CallNo { get; set; }
        public byte BindingTypeEnumId { get; set; }
        public string FileLocation { get; set; }
        public byte SourceEnumId { get; set; }
        public string Pagination { get; set; }
        public string Size { get; set; }
        public string OtherPhysicalDetails { get; set; }
        public Nullable<long> LanguageId { get; set; }
        public byte CategoryEnumId { get; set; }
        public string Remarks { get; set; }
        public string MarcXml { get; set; }
        public byte[] Marc { get; set; }
        public string MarcUrl { get; set; }
        public Nullable<short> CopyrightYear { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
    
        public virtual General_Language General_Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lib_BookDeptMap> Lib_BookDeptMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lib_BookAuthorMap> Lib_BookAuthorMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lib_BookCopy> Lib_BookCopy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lib_BookSubjectMap> Lib_BookSubjectMap { get; set; }
    }
}
