//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_ResultMigration
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public Nullable<long> CurriculumId { get; set; }
        public Nullable<int> DeptBatchId { get; set; }
        public int SemesterId { get; set; }
        public Nullable<long> ClassId { get; set; }
        public string CourseCode { get; set; }
        public Nullable<float> CourseCredit { get; set; }
        public Nullable<float> AttendanceMark { get; set; }
        public Nullable<float> AssignmentMark { get; set; }
        public Nullable<float> MidTermMark { get; set; }
        public Nullable<float> FinalTermMark { get; set; }
        public Nullable<float> TotalMark { get; set; }
        public string Grade { get; set; }
        public Nullable<float> GradePoint { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte TypeEnumId { get; set; }
        public byte StatusEnumId { get; set; }
        public byte ResultGenerateTypeEnumId { get; set; }
        public string Remarks { get; set; }
    }
}
