//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_JoiningSemesterUpdate
    {
        public int Id { get; set; }
        public int ProgramId { get; set; }
        public string ProgramSTitle { get; set; }
        public Nullable<long> StartAdmSemesterIdFor6M { get; set; }
        public Nullable<long> EndAdmSemesterIdFor6M { get; set; }
        public Nullable<long> StartAdmSemesterIdFor4M { get; set; }
        public Nullable<long> EndAdmSemesterIdFor4M { get; set; }
    }
}
