//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_MissingResult
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string UserName { get; set; }
        public int ProgramId { get; set; }
        public long CurriculumId { get; set; }
        public int DeptBatchId { get; set; }
        public string CourseCode { get; set; }
        public float CourseCredit { get; set; }
        public float MidTerm { get; set; }
        public float FinalTerm { get; set; }
        public float Assignment { get; set; }
        public float OralTest { get; set; }
        public float Attendance { get; set; }
        public float TotalMark { get; set; }
        public string Grade { get; set; }
        public float GradePoint { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int AcLgId { get; set; }
        public byte TypeEnumId { get; set; }
        public string EmsCourseCode { get; set; }
        public string Remarks { get; set; }
        public string ResultCode { get; set; }
        public Nullable<float> ResultCredit { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public string RegCode { get; set; }
        public Nullable<float> RegCredit { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> ResultPkId { get; set; }
        public Nullable<int> RegPkId { get; set; }
        public Nullable<int> RegSemesterId { get; set; }
        public Nullable<long> ClassId { get; set; }
    }
}
