//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAC_VerificationAudit
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime InitiatedDate { get; set; }
        public int InitiatedById { get; set; }
        public int Code { get; set; }
        public byte ValidHours { get; set; }
        public string NewDeviceName { get; set; }
        public byte RequestByEnumId { get; set; }
        public byte RequestTypeEnumId { get; set; }
        public byte StatusEnumId { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<int> ConfirmedById { get; set; }
        public string FromIp { get; set; }
        public string Remark { get; set; }
    
        public virtual User_Account User_Account { get; set; }
        public virtual User_Account User_Account1 { get; set; }
        public virtual User_Account User_Account2 { get; set; }
    }
}
