//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Account()
        {
            this.Aca_ClassMaterialFileMap = new HashSet<Aca_ClassMaterialFileMap>();
            this.Aca_CreditTransfer = new HashSet<Aca_CreditTransfer>();
            this.General_AllSmsLog = new HashSet<General_AllSmsLog>();
            this.UAC_PassReset = new HashSet<UAC_PassReset>();
            this.UAC_RoleUserMap = new HashSet<UAC_RoleUserMap>();
            this.UAC_VerificationAudit = new HashSet<UAC_VerificationAudit>();
            this.UAC_VerificationAudit1 = new HashSet<UAC_VerificationAudit>();
            this.UAC_VerificationAudit2 = new HashSet<UAC_VerificationAudit>();
            this.User_ContactAddress = new HashSet<User_ContactAddress>();
            this.User_ContactEmail = new HashSet<User_ContactEmail>();
            this.User_ContactNumber = new HashSet<User_ContactNumber>();
            this.User_Education = new HashSet<User_Education>();
            this.User_Employee = new HashSet<User_Employee>();
            this.User_Experience = new HashSet<User_Experience>();
            this.User_Image = new HashSet<User_Image>();
            this.User_ProfileChangeAudit = new HashSet<User_ProfileChangeAudit>();
            this.User_ProfileChangeAudit1 = new HashSet<User_ProfileChangeAudit>();
            this.User_Publication = new HashSet<User_Publication>();
            this.User_RankHistory = new HashSet<User_RankHistory>();
            this.User_Student = new HashSet<User_Student>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string BanglaName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirthCity { get; set; }
        public Nullable<int> PlaceOfBirthCountryId { get; set; }
        public byte GenderEnumId { get; set; }
        public byte ReligionEnumId { get; set; }
        public byte BloodGroupEnumId { get; set; }
        public byte MaritalStatusEnumId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public string UserMobile { get; set; }
        public string UserMobile2 { get; set; }
        public byte UserMobilePrivacyEnumId { get; set; }
        public bool IsVerifiedUserMobile { get; set; }
        public string UserEmail { get; set; }
        public byte UserEmailPrivacyEnumId { get; set; }
        public bool IsVerifiedUserEmaill { get; set; }
        public string EmergencyContactPersonName { get; set; }
        public string EmergencyMobile { get; set; }
        public string EmergencyContactAdress { get; set; }
        public Nullable<int> EmergencyContactRelationshipId { get; set; }
        public Nullable<float> Height { get; set; }
        public bool IsLate { get; set; }
        public int CampusId { get; set; }
        public string Nationality { get; set; }
        public string NationalIdNumber { get; set; }
        public string BirthCertificateNumber { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string PassportNo { get; set; }
        public byte UserTypeEnumId { get; set; }
        public byte UserStatusEnumId { get; set; }
        public bool IsMigrate { get; set; }
        public string MigrationId { get; set; }
        public bool IsProfileCompleted { get; set; }
        public bool IsUserCanEditProfile { get; set; }
        public bool IsDocumentPending { get; set; }
        public bool IsApproved { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public Nullable<System.DateTime> LastLockoutDate { get; set; }
        public byte FailedPasswordAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAttemptWindowStart { get; set; }
        public byte FailedPasswordAnswerAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAnswerAttemptWindowStart { get; set; }
        public string Remarks { get; set; }
        public string LockReason { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<long> JoiningSemesterId { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string TrackingId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
        public string History { get; set; }
        public string ActiveRfidNo { get; set; }
        public string ProfilePictureImageUrl { get; set; }
        public string SignatureImageUrl { get; set; }
        public bool IsForceTwoFactorAuth { get; set; }
        public bool IsAllowMultiLogin { get; set; }
        public string AuthTokenJson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassMaterialFileMap> Aca_ClassMaterialFileMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_CreditTransfer> Aca_CreditTransfer { get; set; }
        public virtual Aca_Semester Aca_Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<General_AllSmsLog> General_AllSmsLog { get; set; }
        public virtual General_Campus General_Campus { get; set; }
        public virtual General_Country General_Country { get; set; }
        public virtual HR_Department HR_Department { get; set; }
        public virtual Lib_Borrower Lib_Borrower { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAC_PassReset> UAC_PassReset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAC_RoleUserMap> UAC_RoleUserMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAC_VerificationAudit> UAC_VerificationAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAC_VerificationAudit> UAC_VerificationAudit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UAC_VerificationAudit> UAC_VerificationAudit2 { get; set; }
        public virtual User_Relationship User_Relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_ContactAddress> User_ContactAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_ContactEmail> User_ContactEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_ContactNumber> User_ContactNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Education> User_Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Employee> User_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Experience> User_Experience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Image> User_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_ProfileChangeAudit> User_ProfileChangeAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_ProfileChangeAudit> User_ProfileChangeAudit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Publication> User_Publication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_RankHistory> User_RankHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Student> User_Student { get; set; }
    }
}
