//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Rank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Rank()
        {
            this.HR_EmployementHistory = new HashSet<HR_EmployementHistory>();
            this.User_RankHistory = new HashSet<User_RankHistory>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string LocalName { get; set; }
        public string ShortName { get; set; }
        public int Priority { get; set; }
        public byte CategoryEnumId { get; set; }
        public byte JobClassEnumId { get; set; }
        public byte AcademicLevelEnumId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_EmployementHistory> HR_EmployementHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_RankHistory> User_RankHistory { get; set; }
    }
}
