//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Education
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte DegreeEquivalentEnumId { get; set; }
        public int DegreeCategoryId { get; set; }
        public string DegreeTitle { get; set; }
        public byte DegreeGroupMajorEnumId { get; set; }
        public string DegreeGroupMajorOther { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<int> BoardId { get; set; }
        public string CourseDuration { get; set; }
        public Nullable<int> YearOfPassing { get; set; }
        public string RegistrationNo { get; set; }
        public string StudentRollOrIdNo { get; set; }
        public byte ResultSystemEnumId { get; set; }
        public Nullable<float> ObtainedGpaOrMarks { get; set; }
        public string ObtainedGradeOrClass { get; set; }
        public Nullable<float> GpaNo4Sub { get; set; }
        public Nullable<float> FullMarksOrScale { get; set; }
        public Nullable<bool> IsGolden { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
    
        public virtual Adm_DegreeCategory Adm_DegreeCategory { get; set; }
        public virtual Adm_EducationBoard Adm_EducationBoard { get; set; }
        public virtual User_Account User_Account { get; set; }
    }
}
