//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Student()
        {
            this.Aca_ClassAttendance = new HashSet<Aca_ClassAttendance>();
            this.Aca_ClassAttendanceSmsLog = new HashSet<Aca_ClassAttendanceSmsLog>();
            this.Aca_ClassTakenByStudent = new HashSet<Aca_ClassTakenByStudent>();
            this.Aca_ClassWaiverStudent = new HashSet<Aca_ClassWaiverStudent>();
            this.Aca_CreditTransfer = new HashSet<Aca_CreditTransfer>();
            this.Aca_CreditTransferCourses = new HashSet<Aca_CreditTransferCourses>();
            this.Aca_CurriculumStudentMap = new HashSet<Aca_CurriculumStudentMap>();
            this.Aca_ExamRoll = new HashSet<Aca_ExamRoll>();
            this.Aca_HomeWorkSubmission = new HashSet<Aca_HomeWorkSubmission>();
            this.Aca_OnlineExamResultDetail = new HashSet<Aca_OnlineExamResultDetail>();
            this.Aca_OnlineExamTakenByStudent = new HashSet<Aca_OnlineExamTakenByStudent>();
            this.Aca_ProgramTakenByStudent = new HashSet<Aca_ProgramTakenByStudent>();
            this.Aca_StudentRegistration = new HashSet<Aca_StudentRegistration>();
            this.Htl_HostelBuildingStudentMap = new HashSet<Htl_HostelBuildingStudentMap>();
            this.Htl_StudentMealCancel = new HashSet<Htl_StudentMealCancel>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ClassRollNo { get; set; }
        public string RegistrationNo { get; set; }
        public string RegistrationSession { get; set; }
        public int GradingPolicyId { get; set; }
        public float CGPA { get; set; }
        public float CourseCompleted { get; set; }
        public float CreditCompleted { get; set; }
        public float IncompleteCredits { get; set; }
        public float CreditTransfer { get; set; }
        public float CreditWaiver { get; set; }
        public Nullable<int> LevelTermId { get; set; }
        public int ProgramId { get; set; }
        public int ContinuingBatchId { get; set; }
        public byte ClassTimingGroupEnumId { get; set; }
        public int FeeCodeId { get; set; }
        public bool IsFeesVerified { get; set; }
        public long CurriculumId { get; set; }
        public Nullable<long> MajorCurriculumId { get; set; }
        public Nullable<long> SecondMajorCurriculumId { get; set; }
        public Nullable<long> MinorCurriculumId { get; set; }
        public Nullable<long> ElectiveCurriculumId { get; set; }
        public Nullable<int> StudentQuotaNameId { get; set; }
        public byte EnrollmentStatusEnumId { get; set; }
        public byte EnrollmentTypeEnumId { get; set; }
        public Nullable<int> ParentsPrimaryJobTypeId { get; set; }
        public string FatherMobile { get; set; }
        public string MotherMobile { get; set; }
        public int AdmissionExamId { get; set; }
        public string AdmissionTestRollNo { get; set; }
        public string AdmissionFormNo { get; set; }
        public byte AdmissionStatusEnumId { get; set; }
        public string AdmissionRemark { get; set; }
        public bool IsAdmissionFeePaid { get; set; }
        public string CertificateRegistrationNo { get; set; }
        public Nullable<System.DateTime> ProvisionalCertificateIssueDate { get; set; }
        public Nullable<System.DateTime> OriginalCertificateIssueDate { get; set; }
        public Nullable<System.DateTime> OriginalTranscriptIssueDate { get; set; }
        public Nullable<long> GraduationSemesterId { get; set; }
        public string DegreeOptained { get; set; }
        public string MajorMinorDegreeText { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateById { get; set; }
        public System.DateTime LastChanged { get; set; }
        public long LastChangedById { get; set; }
        public bool IsDeleted { get; set; }
        public float PerCreditFee { get; set; }
        public int ClassSectionId { get; set; }
        public string TranscriptSerialNo { get; set; }
        public string OriginalCertificateSerialNo { get; set; }
        public string OriginalCertificateVerifyNo { get; set; }
        public string ProvisionalCertificateSerialNo { get; set; }
        public string ProvisionalCertificateVerifyNo { get; set; }
        public int JoiningBatchId { get; set; }
        public Nullable<int> PreviousProgramId { get; set; }
        public string PreviousStudentUserName { get; set; }
        public int SemesterDurationEnumId { get; set; }
        public bool IsRequiredCGPACalculation { get; set; }
        public Nullable<System.DateTime> LastCGPASyncTime { get; set; }
        public bool ForceDisableOnlineRegistration { get; set; }
        public bool EnableOpenCreditRegistration { get; set; }
        public string UgcUniqueId { get; set; }
        public bool IsProfileEditLock { get; set; }
        public Nullable<int> MaxEligibleRegistrationSemesterCount { get; set; }
        public Nullable<long> DiscontinueSemesterId { get; set; }
        public float DefaultEnrollmentPeriod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassAttendance> Aca_ClassAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassAttendanceSmsLog> Aca_ClassAttendanceSmsLog { get; set; }
        public virtual Aca_ClassSection Aca_ClassSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassTakenByStudent> Aca_ClassTakenByStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ClassWaiverStudent> Aca_ClassWaiverStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_CreditTransfer> Aca_CreditTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_CreditTransferCourses> Aca_CreditTransferCourses { get; set; }
        public virtual Aca_Curriculum Aca_Curriculum { get; set; }
        public virtual Aca_CurriculumElectiveGroup Aca_CurriculumElectiveGroup { get; set; }
        public virtual Aca_CurriculumElectiveGroup Aca_CurriculumElectiveGroup1 { get; set; }
        public virtual Aca_CurriculumElectiveGroup Aca_CurriculumElectiveGroup2 { get; set; }
        public virtual Aca_CurriculumElectiveGroup Aca_CurriculumElectiveGroup3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_CurriculumStudentMap> Aca_CurriculumStudentMap { get; set; }
        public virtual Aca_DeptBatch Aca_DeptBatch { get; set; }
        public virtual Aca_DeptBatch Aca_DeptBatch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ExamRoll> Aca_ExamRoll { get; set; }
        public virtual Aca_GradingPolicy Aca_GradingPolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_HomeWorkSubmission> Aca_HomeWorkSubmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_OnlineExamResultDetail> Aca_OnlineExamResultDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_OnlineExamTakenByStudent> Aca_OnlineExamTakenByStudent { get; set; }
        public virtual Aca_Program Aca_Program { get; set; }
        public virtual Aca_Program Aca_Program1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_ProgramTakenByStudent> Aca_ProgramTakenByStudent { get; set; }
        public virtual Aca_Semester Aca_Semester { get; set; }
        public virtual Aca_Semester Aca_Semester1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aca_StudentRegistration> Aca_StudentRegistration { get; set; }
        public virtual Aca_StudyLevelTerm Aca_StudyLevelTerm { get; set; }
        public virtual Adm_AdmissionExam Adm_AdmissionExam { get; set; }
        public virtual Adm_ParentsPrimaryJobType Adm_ParentsPrimaryJobType { get; set; }
        public virtual Adm_StudentQuotaName Adm_StudentQuotaName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Htl_HostelBuildingStudentMap> Htl_HostelBuildingStudentMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Htl_StudentMealCancel> Htl_StudentMealCancel { get; set; }
        public virtual User_Account User_Account { get; set; }
    }
}
